version: '3'
services:
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8080:80'
    depends_on:
      - csp
      - vmc
      - vmc-nsx
  csp:
    image: stoplight/prism:3
    volumes:
      - ./vmware-cloud-services.json:/tmp/vmware-cloud-services.json
    command: >
      mock -p 4010 --host 0.0.0.0 /tmp/vmware-cloud-services.json
  vmc:
    image: stoplight/prism:3
    volumes:
      - ./vmware-cloud-on-aws.json:/tmp/vmware-cloud-on-aws.json
    command: >
      mock -p 4010 --host 0.0.0.0 /tmp/vmware-cloud-on-aws.json
  vmc-nsx:
    image: stoplight/prism:3
    volumes:
      - ./nsx-vmc-policy-api.json:/tmp/nsx-vmc-policy-api.json
    command: >
      mock -p 4010 --host 0.0.0.0 /tmp/nsx-vmc-policy-api.json